- name: Create scripts directory
  file:
    path: "/home/{{ target_user }}/scripts"
    state: directory
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: '0755'
    
- name: download script folder from ansible
  synchronize:
    src: ../scripts/
    dest: "/home/{{ target_user }}/scripts/"
    mode: push
  
