- name: Create scripts directory
  file:
    path: /home/user/scripts
    state: directory
    owner: user
    group: user
    mode: '0755'
    
- name: download script folder from ansible
  synchronize:
    src: ../scripts/
    dest: /home/user/scripts/
    mode: push
  
