- name: Install global monitor 
  hosts: monitor
  become: true

  tasks:
    - name: Install package
      apt:
        name:
          - openssh-server
        state: present
        update_cache: yes

    - import_tasks: ../tasks/prometheus.yml
    - import_tasks: ../tasks/grafana.yml
    - import_tasks: ../tasks/caddy.yml
