- name: Generate SSH keys for MPI
  hosts: master
  become: true
  tasks:
    - name: Ensure .ssh directory exists
      ansible.builtin.file:
        path: "/home/{{ target_user }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ target_user }}"
        group: "{{ target_user }}"

    - name: Generate SSH key pair for MPI
      ansible.builtin.openssh_keypair:
        path: "/home/{{ target_user }}/.ssh/id_rsa"
        type: rsa
        size: 2048
        mode: '0600'
        owner: "{{ target_user }}"
        group: "{{ target_user }}"

    - name: Read the public key
      ansible.builtin.slurp:
        src: "/home/{{ target_user }}/.ssh/id_rsa.pub"
      register: public_key

    - name: Set fact for public key content
      ansible.builtin.set_fact:
        mpi_public_key: "{{ public_key.content | b64decode }}"

    - name: Add slave host keys to known_hosts
      ansible.builtin.shell: ssh-keyscan -H {{ hostvars[item].ansible_host }} >> "/home/{{ target_user }}/.ssh/known_hosts"
      loop: "{{ groups['slave'] }}"
      become_user: "{{ target_user }}"
      changed_when: false


- name: Distribute SSH public key to slaves
  hosts: slave
  become: true

  vars:
    master_pubkey: "{{ hostvars[groups['master'][0]].mpi_public_key }}"

  tasks:
    - name: Ensure .ssh directory exists
      ansible.builtin.file:
        path: "/home/{{ target_user }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ target_user }}"
        group: "{{ target_user }}"

    - name: Add master's public key to authorized_keys
      ansible.builtin.authorized_key:
        user: "{{ target_user }}"
        key: "{{ master_pubkey }}"
        state: present